import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODONE: implement keys
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en': {
          'profile': 'Profile',
          'account': 'My Account',
          'language': 'Change Language',
          'Change Theme': 'Change Theme',
          'out': 'Log Out',
          'phone': 'Phone Number: ',
          'street': 'Street Address:',
          'email': 'Email:',
          'edit': 'Edit',
          //Add
          'upa': 'New Product',
          'upad': 'Complete the Product details',
          'n': 'Product Name',
          'hn': 'Enter your Product name',
          'd': 'Product Description',
          'hd': 'Enter your Product Description',
          'c': 'Product Category',
          'hc': 'Enter your Product Category',
          'pr': 'Product Price',
          'hpr': 'Enter your Product Price',
          'q': 'Product Quantity ',
          'hq': 'Enter your Product Quantity',
          'cpn': 'Contact Phone Number',
          'pca': 'Product Contact Account',
          'hpca': 'Enter your Product Contact Account',
          'hcpn': 'Enter your Product Contact Phone Number',
          'Your Product must have a Picture':
              'Your Product must have a Picture',
          'twitter': 'Twitter ',
          'enter twitter': 'Enter your Twitter',
          'add': 'Add',
          'select': 'Select ',
          //splash
          'Shopping Home': 'Shopping Home',
          'Welcome to Shopping Home, Let’s shop!':
              'Welcome to Shopping Home, Let’s shop!',
          'We help people conect with store':
              'We help people connect with stores \naround Syria',
          'We show the easy way to shop':
              'We show the easy way to shop. \nJust stay at home with us',
          'Continue': 'Continue',
          //Sign in success
          'Sign In Success': 'Sign In Success',
          'Go to home': 'Go to home',
          //constans
          'Delete': 'Delete',
          'loading...': 'loading...',
          'Done': 'Done',
          //sign in
          'Sign In': 'Sign In',
          'Welcome Back': 'Welcome Back',
          'Sign in with your email and password':
              'Sign in with your email and password \nor continue with social media',
          'Email': 'Email',
          'Enter your email': 'Enter your email',
          'password': 'password',
          'Enter your password': 'Enter your password',

          'Remember me': 'Remember me',
          'Don\'t have an account?': 'Don\'t have an account? ',
          //forgot password
          'Forgot Password': 'Forgot Password',
          'Please enter your email and we will send \nyou an OTB to return your account':
              'Please enter your email and we will send \nyou an OTB to return your account',
          //Search
          'Search In Products By': 'Search In Products By',
          'Search Product': 'Search Product',
          'Search Results': 'Search Results',
          'Name': 'Name',
          'Category': 'Category',
          'Expiry Date': 'Expiry Date',
          //register
          'Register': 'Register',
          'Register Account': 'Register Account',
          'Complete your details': 'Complete your details',
          'Confirm Password': 'Confirm Password',
          'Re-enter your password': 'Re-enter your password',
          'Complete Your Profile': 'Complete Your Profile',
          'By continuing your confirm that you agree':
              'By continuing your confirm that you agree \nwith our Term and Condition',
          'Complete Profile': 'Complete Profile',
          'First Name': 'First Name',
          'Last Name': 'Last Name',
          'BirthDate': 'BirthDate',
          'Enter your last name': 'Enter your last name',
          'Enter your first name': 'Enter your first name',
          'Phone Number': 'Phone Number',
          'Enter your phone number': 'Enter your phone number',
          'Governorate': 'Governorate',
          'Enter your Governorate': 'Enter your Governorate',
          'Region': 'Region',
          'Enter your Region': 'Enter your Region',
          'Street': 'Street',
          'Enter your Street': 'Enter your Street',
          'Contact Email': 'Contact Email',
          'Enter your contact email': 'Enter your contact email',
          'Facebook URL': 'Facebook URL',
          'Enter your Facebook URL': 'Enter your Facebook URL',
          'Telegram URL': 'Telegram URL',
          'Enter your Telegram URL': 'Enter your Telegram URL',
          'WhatsApp Phone Number': 'WhatsApp Phone Number',
          'Enter your whatsapp phone number':
              'Enter your whatsapp phone number',
          'Skype Phone Number': 'Skype',
          'Enter your skype phone number': 'Enter your skype',
          //profile
          'Logged Out': 'Logged Out',
          'IS Loading...': 'IS Loading...',
          //otb
          'OTP Verification': 'OTP Verification',
          'We sent your code to your email': 'We sent your code to your Email',
          'Resend OTP Code': 'Resend OTP Code',
          'This code will expired in': 'This code will expired in',
          //home
          'Price': 'Price',
          'Likes': 'Likes',
          'Views': 'Views',
          'Home': 'Home',
          'Sort Products By': 'Sort Products By',
          'All Product': 'All Product',
          //Edit
          'Edit profile Details': 'Edit profile Details',
          'Edit your profile details': 'Edit your profile details',
          'Edit': 'Edit',
          'Your Name': 'Your Name',
          'Enter your name': 'Enter your name',
          'Enter your phone Number': 'Enter your phone Number',
          'Street Address': 'Street Address',
          'Enter your Street Address': 'Enter your Street Address',
          'Profile Details': 'Profile Details',
          //edit profuct
          'Product Category': 'Product Category',
          'Enter your Product Category': 'Enter your Product Category',
          'Contact Phone Number': 'Contact Phone Number',
          'Enter your Product Contact Phone Number':
              'Enter your Product Contact Phone Number',
          'Product Contact Account': 'Product Contact Account',
          'Enter your Product Contact Account':
              'Enter your Product Contact Account',
          'Product Quantity': 'Product Quantity',
          'Enter your Product Quantity': 'Enter your Product Quantity',
          'Edit Product Details': 'Edit Product Details',
          'Edit your Product details': 'Edit your Product details',
          'First Discount': 'First Discount',
          'Percent': 'Percent',
          'Enter your Product First Discount Percent':
              'Enter your Product First Discount Percent',
          'Second Discount': 'Second Discount',
          'Enter your Product Second Discount Percent':
              'Enter your Product Second Discount Percent',
          'Third Discount': 'Third Discount',
          'Enter your Product Third Discount Percent':
              'Enter your Product Third Discount Percent',
          'Product Name': 'Product Name',
          'Enter your Product name': 'Enter your Product name',
          'Product Description': 'Product Description',
          'Enter your Product Description': 'Enter your Product Description',
          'Product Price': 'Product Price',
          'Enter your Product Price': 'Enter your Product Price',
          //details
          'Initial Price:': 'Initial Price:',
          'Quantity:': 'Quantity:',
          'Discounts:': 'Discounts:',
          'Date:': 'Date:',
          'Percent:': 'Percent:',
          'Current Price:': 'Current Price:',
          'Category: ': 'Category: ',
          'Expiry Date: ': 'Expiry Date: ',
          'Contact Information:': 'Contact Information:',
          'Account: ': 'Account: ',
          'Phone Number: ': 'Phone Number: ',
          'Add To Cart': 'Add To Cart',
          'Order Quantity :': 'Order Quantity :',
          //Reviews
          'Reviews': 'Reviews',
          'Type Your Review': 'Type Your Review',
          'All Reviews': 'All Reviews',
          'welcome': 'welcome',
          'Enter OTB !!': 'Enter OTB !!',
          //Cart
          'Your Cart': 'Your Cart',
          ' items': ' items',
          'Total:\n': 'Total:\n',
          'Check Out': 'Check Out',
          //Notification
          'Your Notifications': 'Your Notifications',
          'Clear All': 'Clear All',
          //Change Password
          'Change Password': 'Change Password',
          'Change Your Password': 'Change Your Password',
          'Please enter your New Password Then Reenter it \n to Confirm':
              'Please enter your New Password Then Reenter it \n to Confirm',
          //Category
          'All Categories': 'All Categories',
          //My Products
          'My Products': 'My Products',
          //My Wallet
          'My Wallet': 'My Wallet',
          'Current Balance': 'Current Balance',
          'Pay Records': 'Pay Records',
          'Take Records': 'Take Records',
          'Give Records': 'Give Records',
          'Records': 'Records',
          'Balance :': 'Balance :',
          'Date :': 'Date :',
        },

        //Arabic LANGUAGE
        'ar': {
          'profile': 'الملف الشخصي',
          'account': 'حسابي',
          'language': 'تغيير اللغة',
          'Change Theme': 'تغيير الثيمة',
          'out': 'تسجيل خروج',
          'phone': 'رقم الهاتف:',
          'street': 'العنوان:',
          'email': 'البريد الالكتروني:',
          'edit': 'تعديل',
          //Add
          'upa': 'منتج جديد',
          'upad': 'ادخل تفاصيل المنتج',
          'n': 'اسم المنتج',
          'hn': 'ادخل اسم المنتج',
          'd': 'تفاصيل المنتج',
          'hd': 'ادخل وصف المنتج',
          'c': 'تصنيف المنتج',
          'hc': 'ادخل تصنيف المنتج',
          'pr': 'سعر المنتج',
          'hpr': 'ادخل سعر المنتج',
          'q': 'كمية المنتج ',
          'hq': 'ادخل كمية المنتج',
          'cpn': 'رقم الهاتف التواصل',
          'pca': 'حساب التواصل',
          'hpca': 'ادخل حساب للتواصل ',
          'hcpn': 'ادخل رقم هاتف للتواصل',
          'Your Product must have a Picture': 'يجب أن يمتلك منتجك صورة',
          'twitter': 'تويتر ',
          'enter twitter': 'ادخل حساب التويتر',
          'add': 'إضافة',
          'select': ' اختر',
          //splash
          'Shopping Home': 'منزل التسوق',
          'Welcome to Shopping Home, Let’s shop!':
              '! أهلا بك في منزل التسوق ، دعنا نتسوق',
          'We help people conect with store':
              'نساعد الناس للتواصل مع المتاجر\n حول سوريا',
          'We show the easy way to shop':
              'لدينا أفضل وأسهل طريقة للتسوق\n ابقى معنا في المنزل',
          'Continue': 'استمر',

          //Sinin success
          'Sign In Success': 'تم تسجيل الدخول بنجاح',
          'Go to home': 'الصفحة الرئيسية',
          //constans
          'Delete': 'حذف',
          'loading...': '...يتم التحميل',
          'Done': 'تم',
          //sinin
          'Sign In': 'تسجيل الدخول',
          'Welcome Back': 'أهلا بك',
          'Sign in with your email and password':
              'أو عبر مواقع التواصل\n قم بتسجيل الدخول عبر حسابك  ',
          'Email': 'الحساب',
          'Enter your email': ' ادخل حسابك ',
          'password': 'كلمة المرور',
          'Enter your password': 'ادخل كلمة المرور',
          'Remember me': 'تذكرني',
          'Don\'t have an account?': 'لست تملك حساب؟ ',
          //forgot password
          'Forgot Password': 'نسيت كلمة المرور ',
          'Please enter your email and we will send \nyou an OTB to return your account':
              'الرجاء ادخال بريدك الالكتروني و نحن سوف نرسل \nلك رمز لاستعادة حسابك',
          //Search
          'Search In Products By': 'البحث عن المنتج حسب ',
          'Search Product': 'البحث',
          'Search Results': 'نتائج البحث',
          'Name': 'الاسم',
          'Category': 'التصنيف',
          'Expiry Date': 'تاريخ انتهاء الصلاحية',
          //register
          'Register': 'حساب جديد',
          'Register Account': 'إنشاء حساب جديد',
          'Complete your details': 'أكمل معلوماتك',
          'Confirm Password': 'تأكيد كلمة المرور',
          'Re-enter your password': 'إعادة ادخال كلمة المرور',
          'Complete Your Profile': 'أكمل ملفك الشخصي',
          'By continuing your confirm that you agree':
              ' استمر مع التاكيد على الموافقة\n على شروطنا ',
          'Complete Profile': 'تكملة الملف الشخصي',
          'First Name': 'الاسم الاول',
          'Last Name': 'الكنية',
          'BirthDate': 'تاريخ الميلاد',
          'Enter your last name': 'ادخل الكنية',
          'Enter your first name': 'ادخل الاسم الاول',
          'Phone Number': 'رقم الهاتف',
          'Enter your phone number': 'ادخل رقم الهاتف',
          'Governorate': 'المحافظة',
          'Enter your Governorate': 'ادخل محافظتك',
          'Region': 'المنطقة',
          'Enter your Region': 'ادخل منطقتك',
          'Street': 'الشارع',
          'Enter your Street': 'ادخل شارعك',
          'Contact Email': 'حساب التواصل',
          'Enter your contact email': 'ادخل حساب التواصل',
          'Facebook URL': 'رابط الفيسبوك',
          'Enter your Facebook URL': 'ادخل رابط حسابك في الفيسبوك',
          'Telegram URL': 'رابط التيليغرام',
          'Enter your Telegram URL': 'ادخل رابط حسابك في التيليغرام',
          'WhatsApp Phone Number': 'رقم هاتف واتساب',
          'Enter your whatsapp phone number': 'ادخل رقم هاتف واتساب الخاص بك',
          'Skype Phone Number': 'سكايب',
          'Enter your skype phone number': 'ادخل سكايب الخاص بك',
          //profile
          'Logged Out': 'تم تسجيل الخروج بنجاح',
          'IS Loading...': '...يتم التحميل',
          //otb
          'OTP Verification': 'رمز التحقق',
          'We sent your code to your email': 'أرسلنا لك رمز التحقق على حسابك',
          'Resend OTP Code': 'إعادة ارسال رمز التحقق',
          'This code will expired in': 'هذا الكود سينتهي في',
          //home
          'Price': 'السعر',
          'Likes': 'الاعجابات',
          'Views': 'مشاهدات',
          'Home': 'الصفحة الرئيسية',
          'Sort Products By': 'ترتيب المنتجات حسب',
          'All Product': 'جميع المنتجات',
          //Edit
          'Edit profile Details': 'تعديل الملف الشخصي',
          'Edit your profile details': 'تعديل معلوماتك الشخصية',
          'Edit': 'تعديل',
          'Your Name': 'اسمك',
          'Enter your name': 'ادخل اسمك',
          'Enter your phone Number': 'ادخل رقم الهاتف',
          'Street Address': 'العنوان',
          'Enter your Street Address': 'ادخل عنوانك',
          'Profile Details': 'تفاصيل الملف الشخصي',
          //edit profuct
          'Product Category': 'تصنيف المنتج',
          'Enter your Product Category': 'ادخل تصنيف المنتج',
          'Contact Phone Number': 'رقم التواصل',
          'Enter your Product Contact Phone Number': 'ادخل رقم التواصل للمنتج',
          'Product Contact Account': 'حساب التواصل',
          'Enter your Product Contact Account': ' ادخل حساب التواصل للمنتج',
          'Product Quantity': 'كمية المنتج',
          'Enter your Product Quantity': 'ادخل كمية المنتج',
          'Edit Product Details': 'تعديل تفاصيل المنتج',
          'Edit your Product details': 'تعديل تفاصيل منتجك',
          'First Discount': 'تاريخ الحسم الاول',
          'Percent': 'نسبة الحسم',
          'Enter your Product First Discount Percent': 'ادخل نسبة الحسم الاول',
          'Second Discount': 'تاريخ الحسم الثاني',
          'Enter your Product Second Discount Percent':
              'ادخل نسبة الحسم الثاني',
          'Third Discount': 'تاريخ الحسم الثالث',
          'Enter your Product Third Discount Percent': 'ادخل نسبة الحسم الثالث',
          'Product Name': 'اسم المنتج',
          'Enter your Product name': 'ادخل اسم المنتج',
          'Product Description': 'وصف المنتج',
          'Enter your Product Description': 'ادخل وصف المنتج ',
          'Product Price': 'سعر المنتج',
          'Enter your Product Price': 'ادخل سعر المنتج',
          //details
          'Initial Price:': ' السعر الاولي:',
          'Quantity:': ' الكمية:',
          'Discounts:': ' الحسومات:',
          'Date:': ' تاريخ:',
          'Percent:': ' النسبة:',
          'Current Price:': ' السعر الحالي:',
          'Category: ': ' التصنيف:',
          'Expiry Date: ': ' تاريخ انتهاء الصلاحية: ',
          'Contact Information:': ' معلومات التواصل:',
          'Account: ': ' الحساب: ',
          'Phone Number: ': ' رقم الهاتف:',
          'Add To Cart': 'اضافة الى السلة',
          'Order Quantity :': 'كمية الطلب :',
          //Reviews
          'Reviews': 'التقييمات',
          'Type Your Review': 'اكتب تقييمك',
          'All Reviews': 'كل التقييمات',
          'welcome': 'مرحيا',
          'Enter OTB !!': 'ادخل رمز التحقق !!',
          //Cart
          'Your Cart': 'سلتك',
          ' items': 'اغراض ',
          'Total:\n': 'المجموع:\n',
          'Check Out': 'دفع المبلغ',
          //Notification
          'Your Notifications': 'اشعاراتك',
          'Clear All': 'مسح الجميع',
          //Change Password
          'Change Password': 'تغيير كلمة السر',
          'Change Your Password': 'تغيير كلمة سرك',
          'Please enter your New Password Then Reenter it \n to Confirm':
              'الرجاع ادخال كلمة سرك الجديدة ثم اعد ادخالها \n للتأكيد',
          //Category
          'All Categories': 'كل المجموعات',
          //My Products
          'My Products': 'منتجاتي',
          //My Wallet
          'My Wallet': 'محفظتي',
          'Current Balance': 'الرصيد الحالي',
          'Pay Records': 'سجلات الدفع',
          'Take Records': 'سجلات الاخذ',
          'Give Records': 'سجلات المنح',
          'Records': 'سجلات',
          'Balance :': 'الرصيد :',
          'Date :': 'التاريخ :',
        },
      };
}
